//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryBoxFarmacy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PeriodoVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["PeriodoVentanaDespuesDeOperacion"]));
            }
            set {
                this["PeriodoVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RolVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["RolVentanaDespuesDeOperacion"]));
            }
            set {
                this["RolVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsuarioVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["UsuarioVentanaDespuesDeOperacion"]));
            }
            set {
                this["UsuarioVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color MyColorSetting {
            get {
                return ((global::System.Drawing.Color)(this["MyColorSetting"]));
            }
            set {
                this["MyColorSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DefaultColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultColor"]));
            }
            set {
                this["DefaultColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TasaDeCambioVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["TasaDeCambioVentanaDespuesDeOperacion"]));
            }
            set {
                this["TasaDeCambioVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TipoDeEntidadVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["TipoDeEntidadVentanaDespuesDeOperacion"]));
            }
            set {
                this["TipoDeEntidadVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProveedoresVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["ProveedoresVentanaDespuesDeOperacion"]));
            }
            set {
                this["ProveedoresVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContactoVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["ContactoVentanaDespuesDeOperacion"]));
            }
            set {
                this["ContactoVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LaboratorioVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["LaboratorioVentanaDespuesDeOperacion"]));
            }
            set {
                this["LaboratorioVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TipoDeUbicacionVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["TipoDeUbicacionVentanaDespuesDeOperacion"]));
            }
            set {
                this["TipoDeUbicacionVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UbicacionVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["UbicacionVentanaDespuesDeOperacion"]));
            }
            set {
                this["UbicacionVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CategoriaVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["CategoriaVentanaDespuesDeOperacion"]));
            }
            set {
                this["CategoriaVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlmacenVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["AlmacenVentanaDespuesDeOperacion"]));
            }
            set {
                this["AlmacenVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SeccionVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["SeccionVentanaDespuesDeOperacion"]));
            }
            set {
                this["SeccionVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProductoPresentacionVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["ProductoPresentacionVentanaDespuesDeOperacion"]));
            }
            set {
                this["ProductoPresentacionVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProductoUnidadDeMedidaVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["ProductoUnidadDeMedidaVentanaDespuesDeOperacion"]));
            }
            set {
                this["ProductoUnidadDeMedidaVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProductoVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["ProductoVentanaDespuesDeOperacion"]));
            }
            set {
                this["ProductoVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TipoDeSalidaVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["TipoDeSalidaVentanaDespuesDeOperacion"]));
            }
            set {
                this["TipoDeSalidaVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TiposDeEntradasVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["TiposDeEntradasVentanaDespuesDeOperacion"]));
            }
            set {
                this["TiposDeEntradasVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BancosVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["BancosVentanaDespuesDeOperacion"]));
            }
            set {
                this["BancosVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContenedorVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["ContenedorVentanaDespuesDeOperacion"]));
            }
            set {
                this["ContenedorVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LocacionVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["LocacionVentanaDespuesDeOperacion"]));
            }
            set {
                this["LocacionVentanaDespuesDeOperacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BodegaVentanaDespuesDeOperacion {
            get {
                return ((bool)(this["BodegaVentanaDespuesDeOperacion"]));
            }
            set {
                this["BodegaVentanaDespuesDeOperacion"] = value;
            }
        }
    }
}
